### ISSUE TITLE
Build needed data model for analysis results

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#113]
- We should have a `AnalysisBatch` just like we have the concept of `PreprocessingBatch`, to allow running analysis more than once with different settings, and to allow us to handle errors that arise during analysis runs, and provide the notion of an analysis batch ID so that we know which run it was that generated various artifacts later on.
- `AnalysisResult`: represents the results of an AnalysisBatch that ran successfully. Contains:
  - associated AnalysisBatch ID
  - link to download the zipped up results
  - pointer to list of `CorrelationResult`s. there will be one of these for each variable (e.g. age, CDR, etc.)
- `CorrelationResult`: Has the correlation analysis information for a specific variable. Contains:
  - id of associated `AnalysisResult`
  - variable name (e.g. age, CDR, etc.)
  - links to nifti images of correlation values (one for allocation, one for transport, and one for vbm)
  - link to nifti images of p-values (again one for allocation, one for transport, and one for vbm)
  - link to atlas

@AlmightyYakob What do you think of an organization like this? Let's iterate on this from here. Maybe `AnalysisResult` is redundant and could be merged into `AnalysisBatch`?

**Comment by ebrahimebrahim** [comment]
@AlmightyYakob This makes a lot of sense. I didn't realize you can stick a json/dictionary structure into one of these django data model things. This organization looks great!

**Comment by AlmightyYakob** [comment]
It seems some revision of the preprocessed image models is needed. In short, the following will take place as a part of addressing this issue:

* The `atlas` field on each preprocessed image will be migrated into the associated preprocessing batch, and removed from the images themselves.
* For the `AnalysisResult` model, the `atlas` isn't actually needed, as it's already stored on the preprocessing batch. We can just point to (likely join) that whenever needed.
