### ISSUE TITLE
Create initial UI layout in the analysis results visualization

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#114]
Add a button that takes you to a page for analysis visualization that can be accessed from the analysis tab. Or we can stick the visualization within the analysis tab. Let's also leave a place for the download button to download zipped up results.

For reference, here's a screenshot of the Rshiny app that we are replacing. We don't have to follow this old layout at all, just whatever makes sense.

![image](https://user-images.githubusercontent.com/1879759/190530992-4bef15ef-b219-48e5-aa1b-ba3cdf901b07.png)

Create a layout with a UI panel (1,2,3) and a view with 3 render windows for slices (4), and a 3D render window. Make some space for some controls under each render window.

In the UI panel, add a dropdown menu for variables (1), another one for features (2), and a numerical input box (not a slider for now) for p-value threshold (3). Also a load button. Variables should be populated from the variable names found in the ~~list of `CorrelationResult`s on the `AnalysisResult` or `AnalysisBatch`~~ `data` object of the `AnalysisResult` (see #113). Features should be populated with the following options: "mass allocation image", "transport cost image", and "VBM tissue density". The p-value threshold should be restricted to be a number in the interval [0,1], defaulting to 0.05.

Put a color bar and an info area (5) somewhere (i.e. make the space for it).

The render windows for slices and for the 3D view can just be vtk.js cone examples for now, as a placeholder.

The button to download the zipped up analysis results should also still exist somewhere, probably in the UI panel

**Comment by ebrahimebrahim** [comment]
Current status on this issue:
- (1) and (2) are done
- (3) is in the works; it remains to label the p-value slider appropriately and make it be a log-based slider
- (4) is done except:
  - No 3D render view at the moment
    - We plan to add 3D view of the thresholder correlation volume
    - The 3D view will be a tab, so there will be two tabs: Slice View, 3D View
    - If a point has been selected using the click interaction in the Slice view, then we can show that in the 3D view with a little sphere.
    - Have a toggle for showing the atlas in 3D view.
  - axial slice seems to be buggy (the slice index keeps getting reset for some reason)
  - click interaction doesn't exist yet: we want clicking to set slices
- (5) is done except:
  - The bounds text formatting needs some work still
  - The correlation and p-value from the click interaction in (4) needs to be incorporated

**Comment by AlmightyYakob** [comment]
Status update:
* (1), (2) and (3) are done
* (4) is done except:
	* No 3D render view at the moment
		* We plan to add 3D view of the thresholder correlation volume
		* The 3D view will be a tab, so there will be two tabs: Slice View, 3D View
		* If a point has been selected using the click interaction in the Slice view, then we can show that in the 3D view with a little sphere.
		* Have a toggle for showing the atlas in 3D view.
	* axial slice seems to be buggy (the slice index keeps getting reset for some reason)
	* click interaction is a work in progress
* (5) is done except:
	* The correlation and p-value from the click interaction in (4) needs to be incorporated

**Comment by AlmightyYakob** [comment]
Status update:

* (1), (2) and (3) are done
* (4) is done. The 3D render view will be moved to a separate issue.
* (5) is done except for the correlation and p-value display. That will be completed as a part of this issue.
