### ISSUE TITLE
data not uploading

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#24]
When I go to "view demo" then "test dataset" I see no data:

![image](https://user-images.githubusercontent.com/1879759/156599907-a565fc41-0bd2-43ce-82e3-b772adda4324.png)

I tried going to "upload" and uploading `sample_data/oasis_small.csv` but that didn't solve the issue.

I did run
```bash
docker-compose run --rm django ./manage.py populate_db sample_data/oasis_small.csv
```
as described in the readme.

When I go to "pending uploads" I see some "batches" stuck there not going anywhere.

**Comment by AlmightyYakob** [comment]
It seems the reason for this is that the Images are never created and read in from the `sample_data` folder. In fact, I can't seem to find any code that actually processes an `UploadBatch`. Is there a defined way these should be processed?

**Comment by ebrahimebrahim** [comment]
Judging by the videos demoing this app last year, it seems like it was possible at some point to upload data.

> Is there a defined way these should be processed?

The first actual processing should happen at the Preprocessing tab, which expects data to already be in an "uploaded" state. I would expect that the preprocessing operates on the raw nifti (nii) files, since I am assuming it runs some of the [scripts here](https://github.com/KitwareMedical/UTM/tree/main/python/preprocessing).

**Comment by ebrahimebrahim** [comment]
Closing this based on our chat.

This turned out to be a misunderstanding of how the app works, rather than a bug.
A "PendingUpload" object is waiting for the _user_ to actually upload an image with the corresponding filename.
So the expected workflow is:
- upload csv file, this creates a bunch of PendingUploads
- go to pending uploads and actually upload the corresponding image files
- then you can do preprocessing and then analysis
