### ISSUE TITLE
"login" does not work

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#25]
Clicking on "login" takes me to a page that says

> Error: invalid_request
> Invalid client_id parameter value. 

![image](https://user-images.githubusercontent.com/1879759/156600789-7c33b881-cdc3-4136-a0eb-c6e90ad1bbae.png)

**Comment by banesullivan** [comment]
You need to create an application which will issue a `client_id` to set in your client app. Visit http://localhost:8000/admin/oauth2_provider/application/ and create a new one. 

The settings for your new application should match as follows:
- Redirect URLs: http://localhost:8080/ (trailing slash matters)
- Client type: Public
- Authorization grant type: Authorization code
- Client Secret: empty
- Name: A descriptive name of your choosing

Assuing your client app is a Vue project created from the D&A cookie-cutter:

Create a new file `.env.development.local` in your house environment variables:
Set `VUE_APP_OAUTH_CLIENT_ID` to the value found in your application's "Client ID" field. This value represents a new OAuth2 public client ID.

**Comment by ebrahimebrahim** [comment]
That worked!

After the application to the oauth settings in the django admin page, nothing changed in the files tracked by git. The only commit-able change is the one to `.env.development.local` in the otm-client repo.

I guess the idea is that the oauth setup steps are meant to be done at deployment time. So this was not a bug, but just me not knowing how to set up a temporary developer-level login system. Please let me know if I've misunderstood, and thanks so much for the help!

**Comment by ebrahimebrahim** [comment]
put info into README

**Comment by banesullivan** [comment]
`.env.development.local` should be in the `.gitignore` so that you do not commit sensitive data. I'd add the following lines to the `.gitignore` of the client project if not already there

```
# local env files
.env.local
.env.*.local
```
