### ISSUE TITLE
Replace shiny app with a vtk.js app

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#32]
Replace shiny app by a pure vtk.js app that is integrated with the rest of otm-client

This is a large task and it will be spread out between otm-server and otm-client.
This issue is just to remind us that the task exists-- once we hash out the details of what needs to be done we can open smaller issues in otm-server and otm-client.

The first step is: understand exactly how the shiny app is currently integrated and summarize where the changes need to be made in order to replace it.

**Comment by ebrahimebrahim** [comment]
Here's a way to inspect Rdata files, while the server is running:

start R prompt:
```sh
docker exec -it otm-server_celery_1 R
```

load the Rdata file and list contents:
```R
load(<path to Rdata file on the server>)
ls()
```

Now you can inspect whatever variables have been loaded

**Comment by AlmightyYakob** [comment]
This issue was converted into https://github.com/girder/otm-server/milestone/2
