### ISSUE TITLE
preview the output of segmentation

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#40]
After preprocessing, there should be a way to preview the outputs

e.g. it should be possible to
- preview the registered image and make sure the registration is reasonable
- preview the segmentation and make sure it's reasonable
- look at the jacobian image and/or feature image, to help the user understand exactly what is being input into the analysis

EDIT: The scope of this particular issue has been reduced to previewing the segmentation only.

**Comment by AlmightyYakob** [comment]
Would it make sense to attempt to use vtk.js for this? And/or, would vtk.js even be the right tool for this? Based on [this](https://kitware.github.io/paraview-glance/doc/readers.html) page, it seems that only ITK.js can render `.nii` files.

**Comment by ebrahimebrahim** [comment]
Yes I think it makes sense, and it will be good practice for later approaching #32.



> Based on [this](https://kitware.github.io/paraview-glance/doc/readers.html) page, it seems that only ITK.js can render `.nii` files.

Based on that page it looks like the approach that mimics paraview would be to read the nifti files with itk.js and then visualize them with vtk.js. I haven't used itk.js before; would be nice to know more about this

**Comment by ebrahimebrahim** [comment]
@AlmightyYakob I noticed that if I go to the [paraview glance web app](https://kitware.github.io/paraview-glance/app/) and give it [one of the sample nifti files](https://github.com/girder/otm-server/tree/master/sample_data/images) it loads nicely.

Can we dig into how glance is doing it? [Glance repo](https://github.com/Kitware/paraview-glance)

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob I noticed that if I go to the [paraview glance web app](https://kitware.github.io/paraview-glance/app/) and give it [one of the sample nifti files](https://github.com/girder/otm-server/tree/master/sample_data/images?rgh-link-date=2022-04-28T17%3A57%3A27Z) it loads nicely.
> 
> Can we dig into how glance is doing it? [Glance repo](https://github.com/Kitware/paraview-glance)

Great find! Yes, I think that's a good idea.

**Comment by ebrahimebrahim** [comment]
I think a good first case to look at is previewing segmentations. It could be a slice view showing an overlay of two layers:
1. the original bias-corrected brain-extracted registered image (the output saved [here](https://github.com/girder/otm-server/blob/9a6e6b58035d0b35788cc6e798728cefb014ac9f/optimal_transport_morphometry/core/tasks.py#L84)) and
2. the segmentation label map (the output saved [here](https://github.com/girder/otm-server/blob/9a6e6b58035d0b35788cc6e798728cefb014ac9f/optimal_transport_morphometry/core/tasks.py#L100))

with two sliders:
1. one slider controls which slice is being viewed
2. another slider controls the opacity of the segmentation label map overlay

and maybe the ability to scroll to zoom? What do you think-- is this a reasonable amount of stuff to cram into a popup window?

**Comment by ebrahimebrahim** [comment]
The scope of this particular issue has been reduced to previewing the segmentation only.
