### ISSUE TITLE
preview registered image

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#47]
(still need to figure out exactly how this should work)

**Comment by AlmightyYakob** [comment]
Now: Act similarly to segmented image, but the top image is the registered image, and the bottom image is the T1 atlas.

Possibly later: Investigate if a checkerboard pattern between registered image and T1 atlas can be achieved. This effect: https://www.slicer.org/wiki/Modules:CheckerBoardFilter-Documentation-3.6

**Comment by ebrahimebrahim** [comment]
Here's the ITK filter that does it: https://itk.org/Doxygen/html/classitk_1_1CheckerBoardImageFilter.html
I wonder if itk.js exposes this for use on the nifti images after you load them

**Comment by AlmightyYakob** [comment]
Closed via https://github.com/girder/otm-client/pull/14
