### ISSUE TITLE
missing icon in title bar

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#56]
![image](https://user-images.githubusercontent.com/1879759/156600602-49c6f911-48d0-4ca4-888c-f060278f24b0.png)

**Comment by AlmightyYakob** [comment]
Do you know what icon is supposed to be used?

**Comment by ebrahimebrahim** [comment]
I think we need to make one. This is a placeholder for that task.

**Comment by ebrahimebrahim** [comment]
Maybe for now this image could be used: https://raw.githubusercontent.com/KitwareMedical/UTM/main/Figures/UTM-3D-example.png

But I'd like to make a more symbolic icon-- I can look into this later
