### ISSUE TITLE
Restrict all dataset actions based on permissions

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/otm-server#69]
Currently only some actions are restricted based on the current user's permissions. The following should also be restricted:

* ~~Running preprocessing~~
* ~~Running analysis~~
* Upload
* Image access? (Not sure what should happen here)

**Comment by AlmightyYakob** [comment]
> Image access should be restricted yes. If a user uploads an image to a non-public dataset, then access to that image should be restricted to that user and their collaborators.

So should images access just follow the same permissions model?

* If dataset is public, readonly access is allowed
* If the user has access to the dataset (owner or collaborator), read/write access is allowed,
* Otherwise, no access is allowed

Is that correct? And furthermore, does that also apply to the preprocessing / analysis output?

**Comment by ebrahimebrahim** [comment]
Yes, that's all correct, and yes it applies to the output images as well.

**Comment by AlmightyYakob** [comment]
The running of analysis and preprocessing has been fixed via #70, so now all that's left is to apply the permission model to:

* Images
* All individual preprocssed image endpoints (or rework them)
* Pending Uploads
* Upload Batches
