### ISSUE TITLE
Make pending uploads page more intuitive

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#75]
Currently it's not very intuitive what to do when you get to the page of a pending uploads batch.
(See for example [our confusion from earlier](https://github.com/girder/otm-server/issues/24))
The instructions/video will help, but it would be better if the page were also more self-explanatory.

- I think part of the confusion is the terminology "Pending uploads". It sounds like it's a process that's ongoing in the background, rather than something the user needs to interact with to get to the next step. Maybe a different phrasing like "Files ready to be uploaded". The API can still call them PendingUploads and just the text on the page can change.
- The layout can be adjusted, perhaps moving the "drag and drop files" box to the bottom. IDK if this helps
- There can be some text added to the page. Something like "To start the upload process, click there and select the image NIfTI files with the filenames listed below.

**Comment by ebrahimebrahim** [comment]
Here's a good plan we agreed on:
- change tab names to "upload table" and "upload images" (the latter is still internally referred to as "pending uploads")
- hide "upload images" tab when there are no pending upload batches to deal with
- move "images" tab to 3rd place, and make it so that you land at "upload table" tab rather than "images" after dataset creation
- add text to "pending uploads" page that makes it clear what user needs to do, what file formats are expected, etc.

**Comment by ebrahimebrahim** [comment]
The first four items are handled by https://github.com/girder/otm-server/issues/72

The last item I don't know how to do properly:
- hide "upload images" tab when there are no pending upload batches to deal with

@AlmightyYakob can you help with that last one? TY!

Also, another thing that would help make things intuitive:
- when user is finished with all pending uploads, they should get redirected out of the pending uploads batch page and to the `dataset/[id]/images` page. because right now you just have to know to back out of the pending uploads batch page to get to the next step.

**Comment by AlmightyYakob** [comment]
Closed via https://github.com/girder/otm-client/pull/18
