### ISSUE TITLE
Improve handling of failed / killed tasks

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/otm-server#78]
Follow up from #76 

Currently, any time a task fails, the status is stuck as `Running`. This should be updated, so that this only occurs if the celery worker itself is killed, due to external factors (out of memory, etc.).

**Comment by ebrahimebrahim** [comment]
also include alerting the user that preprocessing has failed when it does

**Comment by AlmightyYakob** [comment]
The task should also be updated to update the Dataset preprocessing status on failure, and store the error messages. This can be done easily with celery's [`on_failure`](https://docs.celeryq.dev/en/latest/reference/celery.app.task.html#celery.app.task.Task.on_failure) argument.
