### ISSUE TITLE
Restructure tabs on dataset page to not be individually routed

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/otm-server#82]
Original comment: https://github.com/girder/otm-server/issues/75#issuecomment-1208405246

Right now, the tabs being individually routed is causing some issues. Among other things, this change should solve also address the following:

* hide "upload images" tab when there are no pending upload batches to deal with
* when user is finished with all pending uploads, they should get redirected out of the pending uploads batch page and to the dataset/[id]/images page. because right now you just have to know to back out of the pending uploads batch page to get to the next step.

**Comment by ebrahimebrahim** [comment]
adding that we expect this to also help fix #79
