### ISSUE TITLE
display preprocessing status of dataset

### ISSUE THREAD

**Issue by ebrahimebrahim** [girder/otm-server#89]
- display preprocessing status of dataset on the preprocessing page
- display progress (which image is currently being worked on, how many are complete as a percentage or w/e)

**Comment by AlmightyYakob** [comment]
I think to address this short term I'll do it client side. I'm realizing now that when it comes to running preprocessing multiple times, we're not equipped to handle multiple runs, and we need to do a bit of a model refactor to accommodate for that (essentially, just adding a `PreprocessingBatch` model, that keeps track of separate runs of preprocessing).

But ignoring those issues for now, on a single run of preprocessing, client side tracking will suffice.
